<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';require dirname(__DIR__).'/app/Helpers/url.php';
use App\Services\QuizService;use App\Services\QuizDbService;use App\Services\QuizAdminAuthService;use App\Services\QuizBrowserEvaluator as Browser;
final class BrowserFixture extends QuizService{public int $clock=100000;protected function now():string{return gmdate('Y-m-d H:i:s',$this->clock);}}
$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'ple-browser-'.bin2hex(random_bytes(5));mkdir($tmp,0700,true);
try{
 $_SESSION=[];$database=new QuizDbService($tmp);$db=$database->pdo();$auth=new QuizAdminAuthService($database,false);$owner=$auth->createAdmin('owner@example.test','Owner','owner-password','quiz_admin',false);$other=$auth->createAdmin('other@example.test','Other','other-password','quiz_admin',false);
 $quiz=new BrowserFixture($database,['branding'=>['quiz_hmac_secret'=>str_repeat('p',64)]],$tmp);$quiz->setAdminContext($owner);
 $rules=['title'=>'Browser fixture','google_form_url'=>'https://docs.google.com/forms/d/e/PRIVATE_FORM/viewform','attempt_entry_id'=>'123456','duration_minutes'=>15,'max_incidents'=>2,'min_away_seconds'=>10];
 $sid=(int)$quiz->createSession($rules,"Alice Alpha alice@example.test\nBob Beta bob@example.test")['id'];$session=static fn():array=>$quiz->getSession($sid);$gen=static fn():string=>$quiz->getSession($sid)['tracking_generation'];$rev=static fn():int=>(int)$quiz->getSession($sid)['settings_revision'];
 $reject=static function(callable $call,string|array $code)use($db):void{try{$call();throw new LogicException('Expected refusal');}catch(RuntimeException $e){assertSameValue(true,in_array($e->getMessage(),(array)$code,true),'Refusal '.$e->getMessage());}assertSameValue(false,$db->inTransaction(),'No transaction left open');};
 assertSameValue(0,(int)$session()['browser_enabled'],'New/migrated quizzes browseroff');$reject(static fn()=>$quiz->setBrowserPolicy($sid,true,Browser::FAMILIES,$rev(),'Requires active tracking'),'browser_requires_tracking');
 $quiz->setTrackingMode($sid,'continuous',$rev(),'Fictitious continuous');$quiz->openLobby($sid);$students=$quiz->listStudents($sid);$attempt=$quiz->joinAttempt($session(),$students[0]['code']);$aid=(int)$attempt['id'];$student=(int)$attempt['student_id'];$_SESSION['quiz_attempt_id']=$aid;$quiz->launch($sid);$epoch=$quiz->openTrackingRoomDocument($sid,$aid);
 $chrome='Mozilla/5.0 AppleWebKit/537.36 Chrome/151.0.0.0 Safari/537.36';$firefox='Mozilla/5.0 Gecko/20100101 Firefox/144.0';$browser=['user_agent'=>$chrome,'brands'=>[['brand'=>'Chromium','version'=>'150'],['brand'=>'Google Chrome','version'=>'151']],'capabilities'=>array_fill_keys(Browser::CAPABILITIES,true)];
 $quiz->setBrowserRequestUserAgent($chrome);$seven=array_fill_keys(['listener_roundtrip','trusted_enter_received','hidden_received','visible_after_hidden_received','focus_after_hidden_received','fullscreen_change_received','fullscreen_active'],true);$zero=array_fill_keys(array_keys($seven),false);$two=['listener_roundtrip'=>true,'fullscreen_active'=>true];
 $row=static function()use($db,$aid,&$epoch):array{$stmt=$db->prepare("SELECT * FROM quiz_tracking_contexts WHERE attempt_id=:id AND document_epoch_hash=:epoch AND status='active' ORDER BY id DESC LIMIT 1");$stmt->execute(['id'=>$aid,'epoch'=>hash('sha256',$epoch)]);return $stmt->fetch();};
 $pref=static function(array $checks,?array $data)use($quiz,$sid,$aid,$gen,&$epoch):array{$n=$quiz->createTrackingChallenge($sid,$aid,$gen(),$epoch,$data);return $quiz->submitTrackingPreflight($sid,$aid,$gen(),$epoch,$n['challenge'],$checks,$data);};
 $pulse=static function(array $checks,?array $data)use($quiz,$sid,$aid,$gen,&$epoch):array{$n=$quiz->createTrackingPulseChallenge($sid,$aid,$gen(),$epoch,$data);return $quiz->submitTrackingPulse($sid,$aid,$gen(),$epoch,$n['challenge'],$checks,$data);};
 assertSameValue(true,$pref($seven,null)['access_allowed'],'Schema1 legacy works browseroff');assertSameValue(0,(int)$db->query('SELECT COUNT(*) FROM quiz_browser_diagnostics')->fetchColumn(),'Browseroff has no gratuitous diagnostic');
 $initial=$row();$quiz->setBrowserPolicy($sid,true,['safari','chrome','edge','firefox'],$rev(),'Explicit browser pilot');assertSameValue(Browser::FAMILIES,$quiz->getBrowserPolicy($sid)['allowed_families'],'Canonical family order');$reject(static fn()=>$quiz->setTrackingMode($sid,'off',$rev(),'Must disable browser first'),'browser_requires_tracking');
 $reject(static fn()=>$quiz->createTrackingChallenge($sid,$aid,$gen(),$epoch),'schema_invalid');$reject(static fn()=>$quiz->setBrowserPolicy($sid,true,Browser::FAMILIES,$rev(),'No-op'),'browser_policy_unchanged');
 assertSameValue($initial['proof_until'],$row()['proof_until'],'Browser-only policy retains tracking bound');$nonce=$quiz->createTrackingChallenge($sid,$aid,$gen(),$epoch,$browser);$stored=$db->query('SELECT * FROM quiz_tracking_challenges ORDER BY id DESC LIMIT 1')->fetch();assertSameValue('diagnostic_only',$stored['tracking_power'],'Healthy tracking + pending browser fixes diagnostic power');assertSameValue('assessment',$stored['browser_power'],'Browser power fixed independently');
 assertSameValue(true,$quiz->submitTrackingPreflight($sid,$aid,$gen(),$epoch,$nonce['challenge'],$zero,$browser)['access_allowed'],'Sevenfalse browser-only cannot damage healthy tracking');assertSameValue($initial['proof_incarnation'],$row()['proof_incarnation'],'No new tracking incarnation');assertSameValue($initial['proof_until'],$row()['proof_until'],'No tracking extension');assertSameValue('valid',$row()['browser_status'],'Browser assessed separately');
 // Teacher polling/report/export never compares its own request UA with this validation.
 $before=$row();$quiz->setBrowserRequestUserAgent($firefox);$quiz->getTrackingContexts($sid,$aid);$quiz->listBrowserDiagnostics($sid);$quiz->exportCsv($sid);assertSameValue($before,$row(),'Teacher reads cannot modify browser or tracking');$quiz->setBrowserRequestUserAgent($chrome);
 $minor=str_replace('151.0.0.0','151.9.99.7',$chrome);$quiz->setBrowserRequestUserAgent($minor);assertSameValue(true,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Minor variation keeps validation');$quiz->setBrowserRequestUserAgent($chrome.' Chrome/150');assertSameValue(false,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Fresh internally inconsistent HTTP invalidates before URL');$private=$quiz->getTrackingContexts($sid,$aid)['rows'][0]['browser_validation'];assertSameValue(true,in_array('browser_info_inconsistent',$private['details']['causes'],true),'Precise normalized HTTP cause');assertSameValue($initial['proof_until'],$row()['proof_until'],'HTTP change does not shorten or renew tracking');
 $quiz->setBrowserRequestUserAgent($chrome);$pref($zero,$browser);$quiz->setBrowserRequestUserAgent('curl/8.0');$quiz->prepareTrackingState($sid,$aid);assertSameValue(true,in_array('browser_outside_policy',$quiz->getTrackingContexts($sid,$aid)['rows'][0]['browser_validation']['details']['causes'],true),'Outside HTTP cause retained');$quiz->setBrowserRequestUserAgent($chrome);$pref($zero,$browser);
 // Changed result canon refuses without partial consume/renew; browser remains pending.
 $nonce=$quiz->createTrackingPulseChallenge($sid,$aid,$gen(),$epoch,$browser);$before=$row();$changed=$browser;$changed['user_agent']=$firefox;$changed['brands']=null;$quiz->setBrowserRequestUserAgent($firefox);
 $reject(static fn()=>$quiz->submitTrackingPulse($sid,$aid,$gen(),$epoch,$nonce['challenge'],$two,$changed),'browser_environment_changed');assertSameValue($before['proof_until'],$row()['proof_until'],'Changed canon has no partial tracking renewal');assertSameValue('pending',$row()['browser_status'],'Changed canon durable pending');assertSameValue(null,$db->query('SELECT consumed_at FROM quiz_tracking_challenges ORDER BY id DESC LIMIT 1')->fetchColumn(),'Changed canon no consume');$pref($zero,$changed);
 // Browser-only full challenge survives I expiry, without gaining tracking full power.
 $quiz->clock=100050;$quiz->setBrowserPolicy($sid,true,['firefox'],$rev(),'Narrow declared policy');$nonce=$quiz->createTrackingChallenge($sid,$aid,$gen(),$epoch,$changed);$inc=$row()['proof_incarnation'];$quiz->clock=100095;
 assertSameValue(false,$quiz->submitTrackingPreflight($sid,$aid,$gen(),$epoch,$nonce['challenge'],$zero,$changed)['access_allowed'],'Browser assessment survives old I expiry but cannot admit without tracking');assertSameValue('valid',$row()['browser_status'],'Browser remains independently valid');assertSameValue('expired',$row()['proof_status'],'No healthy/TTL invented from diagnostic-only');assertSameValue($inc,$row()['proof_incarnation'],'Old I preserved as expired');$pref($seven,$changed);
 // Fresh required capabilities on even a diagnostic pulse; scopes stay independent.
 $false=$two;$false['listener_roundtrip']=false;$pulse($false,$changed);assertSameValue('failed',$row()['proof_status'],'Pulse tracking failure remains raw');$grant=$quiz->grantTechnicalOverride($sid,$student,$gen(),['browser'],'Browser-only exception');assertSameValue(false,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Browser scope cannot exempt tracking');$quiz->revokeTechnicalOverride($sid,$student,$grant,$gen(),'Revoke browser');$grant=$quiz->grantTechnicalOverride($sid,$student,$gen(),['tracking'],'Tracking-only exception');assertSameValue(true,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Valid browser + exempted tracking admitted');
 $badCaps=$changed;$badCaps['capabilities']['fetch_api']=false;assertSameValue(false,$pulse($two,$badCaps)['access_allowed'],'Diagnostic-only pulse refreshes capabilities and blocks browser');assertSameValue('failed',$row()['proof_status'],'Diagnostictrue never repairs tracking');assertSameValue('failed',$row()['browser_status'],'Actual browser cause preserved');$quiz->revokeTechnicalOverride($sid,$student,$grant,$gen(),'Revoke tracking');$grant=$quiz->grantTechnicalOverride($sid,$student,$gen(),['tracking','browser'],'Both scopes');assertSameValue(true,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Two scopes only final permission');$quiz->setManualAccess($sid,$student,true,'Manual absolute');assertSameValue(false,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'Manual wins');$quiz->setManualAccess($sid,$student,false,'Lift manual');$quiz->revokeTechnicalOverride($sid,$student,$grant,$gen(),'Restore full checks');$pref($seven,$changed);
 // Rollback after tracking mutation and nonce consumption, plus atomic teacher audit failure.
 $tables=static function()use($db):array{$out=[];foreach(['quiz_sessions','quiz_tracking_contexts','quiz_tracking_challenges','quiz_tracking_diagnostics','quiz_browser_diagnostics','quiz_session_audit']as$table){$out[$table]=$db->query('SELECT * FROM '.$table.' ORDER BY id')->fetchAll();}return$out;};
 $quiz->clock+=10;$nonce=$quiz->createTrackingPulseChallenge($sid,$aid,$gen(),$epoch,$changed);$before=$tables();$db->exec("CREATE TRIGGER fail_browser BEFORE INSERT ON quiz_browser_diagnostics WHEN NEW.operation='pulse' BEGIN SELECT RAISE(ABORT,'browser_failure'); END");try{$quiz->submitTrackingPulse($sid,$aid,$gen(),$epoch,$nonce['challenge'],$two,$changed);throw new LogicException('SQL failure expected');}catch(PDOException $e){assertSameValue(true,str_contains($e->getMessage(),'browser_failure'),'Injected browser diagnostic failure');}finally{$db->exec('DROP TRIGGER fail_browser');}assertSameValue($before,$tables(),'All result state rolls back');
 $before=$tables();$db->exec("CREATE TRIGGER fail_policy BEFORE INSERT ON quiz_session_audit WHEN NEW.action='browser_policy_changed' BEGIN SELECT RAISE(ABORT,'policy_failure'); END");try{$quiz->setBrowserPolicy($sid,false,['firefox'],$rev(),'Policy rollback');throw new LogicException('SQL failure expected');}catch(PDOException $e){assertSameValue(true,str_contains($e->getMessage(),'policy_failure'),'Injected audit failure');}finally{$db->exec('DROP TRIGGER fail_policy');}assertSameValue($before,$tables(),'Policy/revision/pending/diagnostics/audit all roll back');
 // Separate cookies and delayed ordinary queues never evaluate a replaced document's UA.
 $cookieA=$_SESSION;$epochA=$epoch;$goodA=$row();$_SESSION=['quiz_attempt_id'=>$aid];$epoch=$quiz->openTrackingRoomDocument($sid,$aid);assertSameValue(false,$quiz->prepareTrackingState($sid,$aid)['access_allowed'],'CookieB cannot inherit A');$pref($seven,$changed);$oldEpoch=$epoch;$epoch=$quiz->openTrackingRoomDocument($sid,$aid);$pref($seven,$changed);$fresh=$row();$quiz->setBrowserRequestUserAgent($chrome);$quiz->setTrackingRequestEpoch($oldEpoch);
 $metadata=['attempt_id'=>$aid,'tracking_generation'=>$gen(),'event_uid'=>bin2hex(random_bytes(16)),'source'=>'hidden','absence_uid'=>bin2hex(random_bytes(16)),'related_event_uid'=>bin2hex(random_bytes(16)),'duration_ms'=>12000];$ack=$quiz->recordEvent($session(),$quiz->getAttempt($aid),'hidden',12,$metadata);assertSameValue(false,array_key_exists('access_allowed',$ack),'Old ordinary ACK never grants access');assertSameValue($fresh,$row(),'Old ordinary UA cannot invalidate current browser');$quiz->setBrowserRequestUserAgent($firefox);$quiz->setTrackingRequestEpoch($epoch);
 $_SESSION=$cookieA;$epoch=$epochA;$quiz->setTrackingRequestEpoch($epoch);assertSameValue('valid',$row()['browser_status'],'CookieB cannot contaminate A');
 // Ordinary title changes preserve browser validation, invalidate pending by shared revision.
 $nonce=$quiz->createTrackingPulseChallenge($sid,$aid,$gen(),$epoch,$changed);$before=$row();$rules['title']='New title';$quiz->updateSession($sid,$rules);assertSameValue($before['browser_status'],$row()['browser_status'],'Unrelated settings keep browser');$reject(static fn()=>$quiz->submitTrackingPulse($sid,$aid,$gen(),$epoch,$nonce['challenge'],$two,$changed),'settings_revision_mismatch');
 for($i=0;$i<105;++$i){$pulse($two,$changed);}assertSameValue(true,$quiz->listBrowserDiagnostics($sid)['next_before']!==null,'Private history pagination bounded');$csv=$quiz->exportCsv($sid);assertSameValue(true,substr_count($csv,'diagnostic_navigateur')>100,'Complete streamed browser journal beyond100');
 $quiz->resetAndRelaunch($sid);$archive=$quiz->getArchive((int)$quiz->listArchives($sid)['rows'][0]['id']);assertSameValue(true,$archive['snapshot']['browser_policy']['enabled'],'Reset freezes explicit policy');$frozen=end($archive['snapshot']['tracking_contexts']);assertSameValue('valid',$frozen['browser_validation']['status'],'Reset freezes validation before termination');$quiz->prepareTrackingState($sid,$aid);assertSameValue('missing',$row()['browser_status'],'New generation never resurrects browser');
 $public=$quiz->prepareTrackingState($sid,$aid);foreach(['browser_enabled','browser_status','browser_policy','browser_incarnation','environment_fingerprint','browser_power','tracking_power','browser_validation']as$marker){assertSameValue(false,str_contains(json_encode($public),$marker),'Public state has no browser marker');}foreach([$chrome,$firefox,'cookie_binding_hash','document_epoch_hash','secret_hash','environment_fingerprint','browser_incarnation']as$secret){assertSameValue(false,str_contains($csv,$secret),'Private exports have no raw UA or binding secret');}
 $quiz->setAdminContext($other);$reject(static fn()=>$quiz->listBrowserDiagnostics($sid),'resource_not_found');$reject(static fn()=>$quiz->getBrowserPolicy($sid),'resource_not_found');$unbound=new BrowserFixture($database,['branding'=>['quiz_hmac_secret'=>str_repeat('p',64)]],$tmp);$reject(static fn()=>$unbound->listBrowserDiagnostics($sid),'admin_auth_required');
 echo "QuizBrowserPolicyTest: OK (independent powers/expiry/capabilities/HTTP/teacher+queue fences/SQL/cookies/snapshots/privacy/history)\n";
}finally{unset($quiz,$unbound,$database,$db,$auth,$session,$gen,$rev,$reject,$row,$pref,$pulse,$tables,$stmt,$e);gc_collect_cycles();foreach(glob($tmp.DIRECTORY_SEPARATOR.'*')?:[]as$file){if(is_file($file)){unlink($file);}}rmdir($tmp);}
